/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -a DownloaderSettingsBridgeAdaptor -c DownloaderSettingsBridgeAdaptor DownloaderSettingsBridge.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include <Host/Dbus/DownloaderSettingsBridgeAdaptor.h>

#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DownloaderSettingsBridgeAdaptor
 */

DownloaderSettingsBridgeAdaptor::DownloaderSettingsBridgeAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DownloaderSettingsBridgeAdaptor::~DownloaderSettingsBridgeAdaptor()
{
    // destructor
}

int DownloaderSettingsBridgeAdaptor::downloadRate() const
{
    // get the value of property downloadRate
    return qvariant_cast< int >(parent()->property("downloadRate"));
}

void DownloaderSettingsBridgeAdaptor::setDownloadRate(int value)
{
    // set the value of property downloadRate
    parent()->setProperty("downloadRate", QVariant::fromValue(value));
}

int DownloaderSettingsBridgeAdaptor::listeningPort() const
{
    // get the value of property listeningPort
    return qvariant_cast< int >(parent()->property("listeningPort"));
}

void DownloaderSettingsBridgeAdaptor::setListeningPort(int value)
{
    // set the value of property listeningPort
    parent()->setProperty("listeningPort", QVariant::fromValue(value));
}

int DownloaderSettingsBridgeAdaptor::maxConnection() const
{
    // get the value of property maxConnection
    return qvariant_cast< int >(parent()->property("maxConnection"));
}

void DownloaderSettingsBridgeAdaptor::setMaxConnection(int value)
{
    // set the value of property maxConnection
    parent()->setProperty("maxConnection", QVariant::fromValue(value));
}

bool DownloaderSettingsBridgeAdaptor::seedEnabled() const
{
    // get the value of property seedEnabled
    return qvariant_cast< bool >(parent()->property("seedEnabled"));
}

void DownloaderSettingsBridgeAdaptor::setSeedEnabled(bool value)
{
    // set the value of property seedEnabled
    parent()->setProperty("seedEnabled", QVariant::fromValue(value));
}

int DownloaderSettingsBridgeAdaptor::torrentProfile() const
{
    // get the value of property torrentProfile
    return qvariant_cast< int >(parent()->property("torrentProfile"));
}

void DownloaderSettingsBridgeAdaptor::setTorrentProfile(int value)
{
    // set the value of property torrentProfile
    parent()->setProperty("torrentProfile", QVariant::fromValue(value));
}

int DownloaderSettingsBridgeAdaptor::uploadRate() const
{
    // get the value of property uploadRate
    return qvariant_cast< int >(parent()->property("uploadRate"));
}

void DownloaderSettingsBridgeAdaptor::setUploadRate(int value)
{
    // set the value of property uploadRate
    parent()->setProperty("uploadRate", QVariant::fromValue(value));
}

