/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -p DownloaderBridgeProxy -c DownloaderBridgeProxy DownloaderBridge.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include <Host/Dbus/DownloaderBridgeProxy.h>

/*
 * Implementation of interface class DownloaderBridgeProxy
 */

DownloaderBridgeProxy::DownloaderBridgeProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DownloaderBridgeProxy::~DownloaderBridgeProxy()
{
}

