/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -V -a MessageAdapterBridgeAdaptor -c MessageAdapterBridgeAdaptor MessageAdapterBridge.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include <Host/Dbus/MessageAdapterBridgeAdaptor.h>
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MessageAdapterBridgeAdaptor
 */

MessageAdapterBridgeAdaptor::MessageAdapterBridgeAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MessageAdapterBridgeAdaptor::~MessageAdapterBridgeAdaptor()
{
    // destructor
}

void MessageAdapterBridgeAdaptor::messageRequestResult(int messageId, int buttonId)
{
    // handle method call local.MessageAdapterBridge.messageRequestResult
    QMetaObject::invokeMethod(parent(), "messageRequestResult", Q_ARG(int, messageId), Q_ARG(int, buttonId));
}

