/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -V -a SettingsBridgeAdaptor -c SettingsBridgeAdaptor SettingsBridge.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include <Host/Dbus/SettingsBridgeAdaptor.h>
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SettingsBridgeAdaptor
 */

SettingsBridgeAdaptor::SettingsBridgeAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SettingsBridgeAdaptor::~SettingsBridgeAdaptor()
{
    // destructor
}

void SettingsBridgeAdaptor::setValue(const QString &path, const QString &key, const QString &data)
{
    // handle method call com.gamenet.dbus.RemoteSettings.setValue
    QMetaObject::invokeMethod(parent(), "setValue", Q_ARG(QString, path), Q_ARG(QString, key), Q_ARG(QString, data));
}

QString SettingsBridgeAdaptor::value(const QString &path, const QString &key, const QString &defValue)
{
    // handle method call com.gamenet.dbus.RemoteSettings.value
    QString out0;
    QMetaObject::invokeMethod(parent(), "value", Q_RETURN_ARG(QString, out0), Q_ARG(QString, path), Q_ARG(QString, key), Q_ARG(QString, defValue));
    return out0;
}

