/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -a DownloaderBridgeAdaptor -c DownloaderBridgeAdaptor DownloaderBridge.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include <Host/Dbus/DownloaderBridgeAdaptor.h>

#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DownloaderBridgeAdaptor
 */

DownloaderBridgeAdaptor::DownloaderBridgeAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DownloaderBridgeAdaptor::~DownloaderBridgeAdaptor()
{
    // destructor
}

void DownloaderBridgeAdaptor::directoryChanged(const QString &serviceId)
{
    // handle method call local.DownloaderBridge.directoryChanged
    QMetaObject::invokeMethod(parent(), "directoryChanged", Q_ARG(QString, serviceId));
}

bool DownloaderBridgeAdaptor::isAnyServiceInProgress()
{
    // handle method call local.DownloaderBridge.isAnyServiceInProgress
    bool out0;
    QMetaObject::invokeMethod(parent(), "isAnyServiceInProgress", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool DownloaderBridgeAdaptor::isInProgress(const QString &serviceId)
{
    // handle method call local.DownloaderBridge.isInProgress
    bool out0;
    QMetaObject::invokeMethod(parent(), "isInProgress", Q_RETURN_ARG(bool, out0), Q_ARG(QString, serviceId));
    return out0;
}

bool DownloaderBridgeAdaptor::isInstalled(const QString &serviceId)
{
    // handle method call local.DownloaderBridge.isInstalled
    bool out0;
    QMetaObject::invokeMethod(parent(), "isInstalled", Q_RETURN_ARG(bool, out0), Q_ARG(QString, serviceId));
    return out0;
}

void DownloaderBridgeAdaptor::pauseSession()
{
    // handle method call local.DownloaderBridge.pauseSession
    QMetaObject::invokeMethod(parent(), "pauseSession");
}

void DownloaderBridgeAdaptor::resumeSession()
{
    // handle method call local.DownloaderBridge.resumeSession
    QMetaObject::invokeMethod(parent(), "resumeSession");
}

void DownloaderBridgeAdaptor::start(const QString &serviceId, int startType)
{
    // handle method call local.DownloaderBridge.start
    QMetaObject::invokeMethod(parent(), "start", Q_ARG(QString, serviceId), Q_ARG(int, startType));
}

void DownloaderBridgeAdaptor::stop(const QString &serviceId)
{
    // handle method call local.DownloaderBridge.stop
    QMetaObject::invokeMethod(parent(), "stop", Q_ARG(QString, serviceId));
}

