/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -p DownloaderBridgeProxy -c DownloaderBridgeProxy DownloaderBridge.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DOWNLOADERBRIDGEPROXY_H_1409555489
#define DOWNLOADERBRIDGEPROXY_H_1409555489

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <Host/Bridge/DownloaderBridge.h>


/*
 * Proxy class for interface local.DownloaderBridge
 */
class DownloaderBridgeProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "local.DownloaderBridge"; }

public:
    DownloaderBridgeProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~DownloaderBridgeProxy();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> directoryChanged(const QString &serviceId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId);
        return asyncCallWithArgumentList(QLatin1String("directoryChanged"), argumentList);
    }

    inline QDBusPendingReply<bool> isAnyServiceInProgress()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("isAnyServiceInProgress"), argumentList);
    }

    inline QDBusPendingReply<bool> isInProgress(const QString &serviceId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId);
        return asyncCallWithArgumentList(QLatin1String("isInProgress"), argumentList);
    }

    inline QDBusPendingReply<bool> isInstalled(const QString &serviceId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId);
        return asyncCallWithArgumentList(QLatin1String("isInstalled"), argumentList);
    }

    inline QDBusPendingReply<> pauseSession()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("pauseSession"), argumentList);
    }

    inline QDBusPendingReply<> resumeSession()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("resumeSession"), argumentList);
    }

    inline QDBusPendingReply<> start(const QString &serviceId, int startType)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId) << QVariant::fromValue(startType);
        return asyncCallWithArgumentList(QLatin1String("start"), argumentList);
    }

    inline QDBusPendingReply<> stop(const QString &serviceId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId);
        return asyncCallWithArgumentList(QLatin1String("stop"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void downloadProgress(const QString &serviceId, int progress, GameNet::Host::Bridge::DownloadProgressArgs args);
    void failed(const QString &serviceId);
    void finished(const QString &serviceId);
    void serviceInstalled(const QString &serviceId);
    void serviceUpdated(const QString &serviceId);
    void started(const QString &serviceId, int startType);
    void statusMessageChanged(const QString &serviceId, const QString &message);
    void stopped(const QString &serviceId);
    void stopping(const QString &serviceId);
    void totalProgress(const QString &serviceId, int progress);
};

namespace local {
  typedef ::DownloaderBridgeProxy DownloaderBridge;
}
#endif
