/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -V -a ApplicationStatisticBridgeAdaptor -c ApplicationStatisticBridgeAdaptor ApplicationStatisticBridge.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef APPLICATIONSTATISTICBRIDGEADAPTOR_H
#define APPLICATIONSTATISTICBRIDGEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.protocolone.launcher.dbus.ApplicationStatistic
 */
class ApplicationStatisticBridgeAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.protocolone.launcher.dbus.ApplicationStatistic")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.protocolone.launcher.dbus.ApplicationStatistic\">\n"
"    <method name=\"isGameInstalled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"serviceId\"/>\n"
"    </method>\n"
"    <method name=\"gameInstallDate\">\n"
"      <arg direction=\"out\" type=\"t\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"serviceId\"/>\n"
"    </method>\n"
"    <method name=\"gameLastExecutionTime\">\n"
"      <arg direction=\"out\" type=\"t\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"serviceId\"/>\n"
"    </method>\n"
"    <method name=\"executeGameSuccessCount\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"serviceId\"/>\n"
"    </method>\n"
"    <method name=\"executeGameFailedCount\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"serviceId\"/>\n"
"    </method>\n"
"    <method name=\"executeGameTotalCount\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"serviceId\"/>\n"
"    </method>\n"
"    <method name=\"installWithService\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"installDate\">\n"
"      <arg direction=\"out\" type=\"t\"/>\n"
"    </method>\n"
"    <method name=\"isFirstStart\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ApplicationStatisticBridgeAdaptor(QObject *parent);
    virtual ~ApplicationStatisticBridgeAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int executeGameFailedCount(const QString &serviceId);
    int executeGameSuccessCount(const QString &serviceId);
    int executeGameTotalCount(const QString &serviceId);
    qulonglong gameInstallDate(const QString &serviceId);
    qulonglong gameLastExecutionTime(const QString &serviceId);
    qulonglong installDate();
    QString installWithService();
    bool isFirstStart();
    bool isGameInstalled(const QString &serviceId);
Q_SIGNALS: // SIGNALS
};

#endif
