/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -p ConnectionBridgeProxy -c ConnectionBridgeProxy ConnectionBridge.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef CONNECTIONBRIDGEPROXY_H_1417514109
#define CONNECTIONBRIDGEPROXY_H_1417514109

#include <Host/Bridge/Credential.h>

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.gamenet.dbus.Connection
 */
class ConnectionBridgeProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.gamenet.dbus.Connection"; }

public:
    ConnectionBridgeProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ConnectionBridgeProxy();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> ping()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("ping"), argumentList);
    }

    inline QDBusPendingReply<> setApplicationName(const QString &applicationName)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(applicationName);
        return asyncCallWithArgumentList(QLatin1String("setApplicationName"), argumentList);
    }

    inline QDBusPendingReply<> terminate()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("terminate"), argumentList);
    }

    inline QDBusPendingReply<> setCredential(GameNet::Host::Bridge::Credential credential)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(credential);
        return asyncCallWithArgumentList(QLatin1String("setCredential"), argumentList);
    }

    inline QDBusPendingReply<> setSecondCredential(GameNet::Host::Bridge::Credential credential)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(credential);
        return asyncCallWithArgumentList(QLatin1String("setSecondCredential"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void pong();
    void wrongCredential(const QString &userId);
};

namespace com {
  namespace gamenet {
    namespace dbus {
      typedef ::ConnectionBridgeProxy Connection;
    }
  }
}
#endif
