/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -V -a MessageAdapterBridgeAdaptor -c MessageAdapterBridgeAdaptor MessageAdapterBridge.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MESSAGEADAPTERBRIDGEADAPTOR_H
#define MESSAGEADAPTERBRIDGEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.MessageAdapterBridge
 */
class MessageAdapterBridgeAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.MessageAdapterBridge")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.MessageAdapterBridge\">\n"
"    <signal name=\"messageRequest\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"messageId\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"title\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"text\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"buttons\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"icon\"/>\n"
"    </signal>\n"
"    <method name=\"messageRequestResult\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"messageId\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"buttonId\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    MessageAdapterBridgeAdaptor(QObject *parent);
    virtual ~MessageAdapterBridgeAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void messageRequestResult(int messageId, int buttonId);
Q_SIGNALS: // SIGNALS
    void messageRequest(int messageId, const QString &title, const QString &text, int buttons, int icon);
};

#endif
