/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -V -a ServiceHandleBridgeAdaptor -c ServiceHandleBridgeAdaptor ServiceHandleBridge.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SERVICEHANDLEBRIDGEADAPTOR_H
#define SERVICEHANDLEBRIDGEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.gamenet.dbus.ServiceHandle
 */
class ServiceHandleBridgeAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.gamenet.dbus.ServiceHandle")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.gamenet.dbus.ServiceHandle\">\n"
"    <signal name=\"locked\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"serviceId\"/>\n"
"    </signal>\n"
"    <signal name=\"unlocked\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"serviceId\"/>\n"
"    </signal>\n"
"    <method name=\"lock\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"serviceId\"/>\n"
"    </method>\n"
"    <method name=\"unlock\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"serviceId\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ServiceHandleBridgeAdaptor(QObject *parent);
    virtual ~ServiceHandleBridgeAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool lock(const QString &serviceId);
    void unlock(const QString &serviceId);
Q_SIGNALS: // SIGNALS
    void locked(const QString &serviceId);
    void unlocked(const QString &serviceId);
};

#endif
