/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -V -p ServiceSettingsBridgeProxy -c ServiceSettingsBridgeProxy ServiceSettingsBridge.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef SERVICESETTINGSBRIDGEPROXY_H
#define SERVICESETTINGSBRIDGEPROXY_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.gamenet.dbus.ServiceSettings
 */
class ServiceSettingsBridgeProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.gamenet.dbus.ServiceSettings"; }

public:
    ServiceSettingsBridgeProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~ServiceSettingsBridgeProxy();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> downloadPath(const QString &serviceId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId);
        return asyncCallWithArgumentList(QStringLiteral("downloadPath"), argumentList);
    }

    inline QDBusPendingReply<qulonglong> gameSize(const QString &serviceId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId);
        return asyncCallWithArgumentList(QStringLiteral("gameSize"), argumentList);
    }

    inline QDBusPendingReply<bool> hasDownloadPath(const QString &serviceId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId);
        return asyncCallWithArgumentList(QStringLiteral("hasDownloadPath"), argumentList);
    }

    inline QDBusPendingReply<QString> installPath(const QString &serviceId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId);
        return asyncCallWithArgumentList(QStringLiteral("installPath"), argumentList);
    }

    inline QDBusPendingReply<bool> isDefaultDownloadPath(const QString &serviceId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId);
        return asyncCallWithArgumentList(QStringLiteral("isDefaultDownloadPath"), argumentList);
    }

    inline QDBusPendingReply<bool> isDefaultInstallPath(const QString &serviceId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId);
        return asyncCallWithArgumentList(QStringLiteral("isDefaultInstallPath"), argumentList);
    }

    inline QDBusPendingReply<bool> isDownloadable(const QString &serviceId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId);
        return asyncCallWithArgumentList(QStringLiteral("isDownloadable"), argumentList);
    }

    inline QDBusPendingReply<bool> isOverlayEnabled(const QString &serviceId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId);
        return asyncCallWithArgumentList(QStringLiteral("isOverlayEnabled"), argumentList);
    }

    inline QDBusPendingReply<bool> isPrefer32Bit(const QString &serviceId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId);
        return asyncCallWithArgumentList(QStringLiteral("isPrefer32Bit"), argumentList);
    }

    inline QDBusPendingReply<QString> name(const QString &serviceId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId);
        return asyncCallWithArgumentList(QStringLiteral("name"), argumentList);
    }

    inline Q_NOREPLY void setDownloadPath(const QString &serviceId, const QString &path)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId) << QVariant::fromValue(path);
        callWithArgumentList(QDBus::NoBlock, QStringLiteral("setDownloadPath"), argumentList);
    }

    inline Q_NOREPLY void setInstallPath(const QString &serviceId, const QString &path)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId) << QVariant::fromValue(path);
        callWithArgumentList(QDBus::NoBlock, QStringLiteral("setInstallPath"), argumentList);
    }

    inline Q_NOREPLY void setOverlayEnabled(const QString &serviceId, bool enabled)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId) << QVariant::fromValue(enabled);
        callWithArgumentList(QDBus::NoBlock, QStringLiteral("setOverlayEnabled"), argumentList);
    }

    inline Q_NOREPLY void setPrefer32Bit(const QString &serviceId, bool value)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(serviceId) << QVariant::fromValue(value);
        callWithArgumentList(QDBus::NoBlock, QStringLiteral("setPrefer32Bit"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace gamenet {
    namespace dbus {
      typedef ::ServiceSettingsBridgeProxy ServiceSettings;
    }
  }
}
#endif
