/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -p UpdateManagerBridgeProxy -c UpdateManagerBridgeProxy UpdateManagerBridge.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef UPDATEMANAGERBRIDGEPROXY_H_1410861382
#define UPDATEMANAGERBRIDGEPROXY_H_1410861382

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.gamenet.dbus.Updater
 */
class UpdateManagerBridgeProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.gamenet.dbus.Updater"; }

public:
    UpdateManagerBridgeProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~UpdateManagerBridgeProxy();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<int> updateState()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("updateState"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void allCompleted(bool isNeedRestart);
    void downloadRetryNumber(int retryNumber);
    void downloadUpdateProgress(qulonglong currentSize, qulonglong totalSize);
    void noUpdatesFound();
    void restartUICallback(bool isMinimized);
    void restartUIRequest();
    void switchClientVersion(bool isMinimized);
    void updateError(int errorCode);
    void updateStateChanged(int updateState);
    void updatesFound();
};

namespace com {
  namespace gamenet {
    namespace dbus {
      typedef ::UpdateManagerBridgeProxy Updater;
    }
  }
}
#endif
